---
global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ['192.168.33.11:9100']

  - job_name: 'example-random'
    static_configs:
      - targets: ['192.168.33.13:8081', '192.168.33.13:8082']
        labels:
          group: 'production'

      - targets: ['192.168.33.13:8083']
        labels:
          group: 'canary'

remote_write:
  - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
  - url: "http://prometheus_postgresql_adapter:9201/read"
